"""Strict specification compliance tests for modbus-connection.

Verifies 100% adherence to:
https://home-assistant-libs.github.io/modbus-connection/
- Connection and unit separation
- Device object pattern (Device subclass over Components)
- Sub-system categorization (READINGS and SETTINGS)
- UpdateReport and fault isolation
- Read event limits and register request bounding
- Zero drift between standalone library (src/foxess_modbus) and vendored integration (custom_components/foxess_modern/device)
"""

import os
from collections.abc import Iterable
import pytest

from modbus_connection.exceptions import (
    ModbusConnectionError,
    ModbusError,
    ModbusTimeoutError,
)
from modbus_connection.model import Component, Device, UpdateReport

from foxess_modbus import (
    FoxessH1Inverter,
    FoxessH3Inverter,
    FoxessH3ProInverter,
    FoxessKH10Inverter,
)
from foxess_modbus.model import FoxessComponent, FoxessDevice

ALL_INVERTER_CLASSES = [
    FoxessKH10Inverter,
    FoxessH1Inverter,
    FoxessH3Inverter,
    FoxessH3ProInverter,
]


def test_device_object_inheritance_spec():
    """Verify all inverters strictly inherit from modbus_connection.model.Device."""
    assert issubclass(FoxessDevice, Device)

    for cls in ALL_INVERTER_CLASSES:
        assert issubclass(cls, FoxessDevice), f"{cls.__name__} must inherit from FoxessDevice"
        assert issubclass(cls, Device), f"{cls.__name__} must inherit from modbus_connection.model.Device"


def test_component_inheritance_and_max_span_spec():
    """Verify subcomponents inherit from Component and respect bounded max_span."""
    assert issubclass(FoxessComponent, Component)
    assert FoxessComponent.max_span == 8, "FoxESS AUX UART FIFO requires bounded max_span <= 8"


def test_constructor_unit_contract_spec(mock_modbus_unit):
    """Verify inverters are instantiated strictly from ModbusUnit."""
    for cls in ALL_INVERTER_CLASSES:
        inv = cls(mock_modbus_unit)
        assert inv.modbus_unit is mock_modbus_unit
        assert hasattr(inv, "async_update_readings")
        assert hasattr(inv, "async_update_settings")
        assert hasattr(inv, "async_update")
        assert hasattr(inv, "async_read_raw")


@pytest.mark.asyncio
async def test_update_methods_return_update_report_spec(mock_modbus_unit):
    """Verify polling methods return UpdateReport as required by modbus-connection."""
    # Seed holding registers for KH10
    mock_modbus_unit.holding[39070] = [2300, 100, 2300, 100, 0, 0, 0, 0]  # PV1-PV4 V & I
    mock_modbus_unit.holding[39279] = [0, 500, 0, 500, 0, 0, 0, 0]         # PV1-PV4 Powers
    mock_modbus_unit.holding[31006] = [2300, 100, 1000, 5000, 0, 0, 0, 0] # Grid telemetry
    mock_modbus_unit.holding[31020] = [5000, 100, 500, 250, 50, 100, 100]  # Battery
    mock_modbus_unit.holding[39168] = [0, 500]                              # CT meter 32-bit
    mock_modbus_unit.holding[32000] = [0, 10, 0, 20, 0, 30, 0, 40]         # Energy
    mock_modbus_unit.holding[30000] = [1, 2, 3, 4]                          # Inverter & versions
    mock_modbus_unit.holding[41001] = [1, 10, 100, 10]                      # Control settings

    inv = FoxessKH10Inverter(mock_modbus_unit)

    report_readings = await inv.async_update_readings()
    assert isinstance(report_readings, UpdateReport)
    assert report_readings.updated

    report_settings = await inv.async_update_settings()
    assert isinstance(report_settings, UpdateReport)

    report_all = await inv.async_update()
    assert isinstance(report_all, UpdateReport)

    raw_data = await inv.async_read_raw()
    assert isinstance(raw_data, dict)


@pytest.mark.asyncio
async def test_read_events_respect_controller_limits_spec(mock_modbus_unit):
    """Verify read events generated by poll respect controller packet limits."""
    # Seed holding registers for KH10
    mock_modbus_unit.holding[39070] = [2300, 100, 2300, 100, 0, 0, 0, 0]
    mock_modbus_unit.holding[39279] = [0, 500, 0, 500, 0, 0, 0, 0]

    inv = FoxessKH10Inverter(mock_modbus_unit)
    await inv.async_update_readings()

    events = mock_modbus_unit.read_events
    assert len(events) > 0
    # Every read block count must be bounded
    for event in events:
        assert event.count <= 100, f"Read count {event.count} exceeded controller limit of 100"
        assert event.register_type == "holding"


@pytest.mark.asyncio
async def test_subsystem_fault_isolation_spec(mock_modbus_unit):
    """Verify a sub-system failure is isolated in report.failed without breaking other components."""
    # Seed registers for pv and grid
    mock_modbus_unit.holding[39070] = [2300, 100, 2300, 100, 0, 0, 0, 0]
    mock_modbus_unit.holding[39279] = [0, 500, 0, 500, 0, 0, 0, 0]
    mock_modbus_unit.holding[31006] = [2300, 100, 1000, 5000, 0, 0, 0, 0]

    # Arm a failure on battery registers (address 31020)
    mock_modbus_unit.fail_read(31020, ModbusError("Refused battery register"))

    inv = FoxessKH10Inverter(mock_modbus_unit)
    report = await inv.async_update_readings()

    # The failing component must land in report.failed
    assert "battery" in report.failed or any("battery" in str(f) for f in report.failed)
    # Successful components still update
    assert "pv" in report.updated or "grid" in report.updated


@pytest.mark.asyncio
async def test_connection_error_propagates_immediately_spec(mock_modbus_unit):
    """Verify ModbusConnectionError propagates immediately rather than landing in report.failed."""
    # Fail read on PV registers (39070)
    mock_modbus_unit.fail_read(39070, ModbusConnectionError("TCP connection lost"))

    inv = FoxessKH10Inverter(mock_modbus_unit)
    with pytest.raises(ModbusConnectionError):
        await inv.async_update_readings()


def test_zero_drift_library_and_integration_spec():
    """Verify standalone library (src/foxess_modbus) and vendored device code are 100% synchronized."""
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    src_dir = os.path.join(repo_root, "src", "foxess_modbus")
    device_dir = os.path.join(repo_root, "custom_components", "foxess_modern", "device")

    assert os.path.exists(src_dir), "src/foxess_modbus directory must exist"
    assert os.path.exists(device_dir), "custom_components/foxess_modern/device must exist"

    for root, _dirs, files in os.walk(src_dir):
        for file in files:
            if file.endswith(".pyc") or file == "py.typed" or "__pycache__" in root:
                continue

            rel_file = os.path.relpath(os.path.join(root, file), src_dir)
            target_file = os.path.join(device_dir, rel_file)

            assert os.path.exists(target_file), f"Vendored device missing file: {rel_file}"

            with open(os.path.join(root, file), "r", encoding="utf-8") as f_src:
                src_content = f_src.read()
            with open(target_file, "r", encoding="utf-8") as f_dev:
                dev_content = f_dev.read()

            # Normalize import depth differences (e.g. from ..model to from ...model)
            norm_src = [
                line.strip()
                for line in src_content.splitlines()
                if not line.strip().startswith(("from ..", "from .", "import "))
            ]
            norm_dev = [
                line.strip()
                for line in dev_content.splitlines()
                if not line.strip().startswith(("from ..", "from .", "import "))
            ]

            assert norm_src == norm_dev, f"Logic drift detected between library and integration in {rel_file}!"
